{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 24ff8ab79233b646b9c3202c6d8afa043af431113910864d7019c3df54b41eb2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
    - setuptools
    - wheel
  run:
    # From upstream: Until the dropbox/PyHive#380 is solved
    # we will exclude hive provider. This will be the next step
    # to add full support and exclusion but we need to merge it first
    # in order to be able to build image from `main`.
    - python >=3.6,<3.9
    - apache-airflow >=2.1.0
    - hmsclient >=0.1.0
    - pandas >=0.17.1,<2.0
    - pyhive >=0.6.0
    - thrift >=0.9.2
    # temporary dependencies because of bad build of thrift_sasl
    - thrift >=0.13
    - pure-sasl >=0.6.2
    - six >=1.13.0

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Hive for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
