{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-hive-{{ version }}.tar.gz
  sha256: b54d3aea220c3095b21133dd4a762e519ba20bcddd8767f77f1ea3693d8af3a3

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - apache-airflow >=2.1.0
    - hmsclient >=0.1.0
    - pandas >=0.17.1
    - pyhive >=0.6.0
    - python
    - sasl >=0.3.1  # [py>=39]
    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-hive package
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
