{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 1ee43ad4e53bf09a99c7cddd7a3383145b5f773b0868e3199e760cd49fa837b0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
    - setuptools
    - wheel
  run:
    # pyhive doesn't yet support python 3.9 correctly: https://github.com/dropbox/PyHive/issues/380
    - python >=3.6,<3.9
    - apache-airflow >=2.1.0
    - hmsclient >=0.1.0
    - pandas >=0.17.1,<1.4
    - pyhive >=0.6.0
    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.10.0
    - thrift_sasl >=0.1.0

    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Hive for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
