{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-hive-{{ version }}.tar.gz
  sha256: e549e1b2e20698c5808e70115896d541119076ace9f397c042e7ac7e829abb44

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - apache-airflow >=2.2.0
    - apache-airflow-providers-common-sql
    - hmsclient >=0.1.0
    - pandas >=0.17.1
    - pyhive >=0.6.0
    - python
    - sasl >=0.3.1  # [py>=39]
    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-apache-hive package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
