{% set name = "apache-airflow-providers-apache-hive" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 0f4b146293816b9c2d3418c73d2a261dfdf46d3f0cd606381a6cb70670cbb509

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - hmsclient >=0.1.0
    - pandas >=0.17.1,<1.4
    - pyhive >=0.6.0
    # pyhive[hive]
    - sasl >=0.2.1
    - thrift >=0.10.0
    - thrift_sasl >=0.1.0

    - sasl >=0.3.1
    - thrift >=0.9.2

test:
  imports:
    - airflow.providers.apache.hive
    - airflow.providers.apache.hive.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Hive for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-hive/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
